source 'git@git.pixio.com:pixio-libraries/specs.git'
source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!

target 'PXGradientView' do
  pod "PXGradientView", :path => "../"
end

target 'Tests' do
  pod "PXGradientView", :path => "../"


end
