source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!

target 'PXGradientViewDemo' do
  pod "PXGradientView", :path => "../"
end

target 'Tests' do
  pod "PXGradientView", :path => "../"
end

target 'PXGradientViewSwiftDemo' do
    pod "PXGradientView", :path => "../"
end

target 'PXGradientViewSwiftDemoTests' do
    pod "PXGradientView", :path => "../"
end
